### ISSUE TITLE
🙏When the best intervention is not to intervene 🙏

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/IH-intervention#13]
### 1. Does this proposal address that some categories may be under rewarded and others over rewarded?

No

### 2. Does this proposal address that paid contributors have had a 50-85% reduction to their total number of impact hours?

No

### 3. Does this proposal address that foundational members of the Token Engineering Community may lack recognition for their less visible work?

No

### 4. Does this proposal address the distribution of impact hours in relation to equality metrics such as the Gini Coefficient?

No

### What interventions are being proposed? 

I propose to not intervine, even aknowedging that some improvements have to be done to the praising system to track contributions in the future.

### What is the reasoning?

1. **Is retweeting over-rewarded?** For sure, but it was an easy entry point for many people, and at some point I guess it looked like a good idea to reward these kind of interactions. It is something easy for everyone to have some tokens and distribute the token among many people.
2. **Impact hour deductions:** At the very beinning it was uncertain that this project were going to succeed and many people took a high risk not being paid for their work. This project wouldn't have been possible without the paid contributors (I praise all of them for that!), but we (me included) have been paid for doing so, and we could choose not to be at any point during the project to be more exposed to IH. It looks unfair now to change the rules of the game at the end of the game. The same applies to governace power: the rules were clear from the beginning, and it has been a long process in which people could choose.
3. **Recognize TE work:** The whole TEC is made to recognize and reward TE work, although IH are made to reward initial contributors to build the commons infrastructure around TE. The whole purpose of the hatch and conviction voting is to fund TE work. After the hatch we can do lots of conviction voting proposals for converting funds from the common pool to TEC tokens in order to reward previous TE work.
4. **Impact Hour distribution equality:** Impact hours are earned hours. UBI can be useful to end extreme poverty, but we are not talking about poverty here. IH is a system to value and recognize contributions, and it would be against its purpose to value contributions without a real impact. Creating a community with a low gini coeficient would be great (it would mean that we have lots of engaged people producing lots of valuable things), but changing the gini coeficient artificially by redistributing the hardly earned rewards doesn't make it.

--- 

🤔 Take a look at [this forum post](https://forum.tecommons.org/t/pre-hatch-impact-hours-distribution-analysis/376/50?u=liviade) if you have any questions.

🗳 When you are finished writing, head over to [TokenLog](https://tokenlog.xyz/TECommons/TokenLog-SoftGov) and vote for your favourite proposals!

**Comment by Zeptimus** [comment]
[MrsBadgerface]
Hey @sembrestels When I read this, I hear a strong sense of what you see as a just and equitable space (not changing the rules partway through; we spent time on decisions and those decisions should be upheld) and while it's not a position that I am able to support, I wanted to acknowledge what's just and equitable for you.

**Comment by Zeptimus** [comment]
[sembrestels]
If you ask me, I don't think the current system is fair. If I could go back to the past I would not agree on many things on the current praise system.

The problem is that I don't believe that there is a solution that would be fair for everyone at this point. This is why I personally think it is better not to intervene with a top-to-down solution.

**Comment by Zeptimus** [comment]
[danelsuga]
@sembrestels Luckily we don't have to go back in the past to improve the malleable systems we've created and put in place. We have the here-and-now to learn from our previous decisions and to improve upon the systems we put in place.

That commitment to excellence by improvement, to community-focused values and to courage with vision and insight is the very heart of the TEC.

We as humans exist in an ever-evolving relationship with the many systems we create and live by. They will never be "perfect", and/but we will continually strive to improve them. That is the nature of moving forward, of ingenuity, of creativity and of valuing the community, which exists and thrives only through our collective being.

**Comment by Zeptimus** [comment]
[LinuxIsCool]
This proposal is lazy. It's the easy way out. It discourages the consideration of the entire space of possible praise augmentations. The memes are candy. Are we rotting our teeth before we are born? Rusting our infrastructure before it is deployed? If the praise system is to be improved, then NOW is the time to improve it.

There are many proposals that do not even modify the current praise data in any way. For example @GriffGreen's solution in which we simply throw a big praise party to praise all the TE rockstars that we cherish. This is using the system itself to heal itself, anti-fragility by self-repair. #2

Also consider @tamarandom's solution for praise categorization, which says, not to change past praise data, but adjust the way that we allocate praise in the future, say, giving a fixed 1% of praise weight to retweets, and 3% praise weight to meeting attendance. This would mean a retweet would be roughly 0.09 IH and attending a meeting would be roughly 0.2 IH. This sounds amazing to me, and allows us to consider how the other 96% of IH are allocated as well. #6

**Comment by Zeptimus** [comment]
[sembrestels]

> Luckily we don't have to go back in the past to improve the malleable systems we've created and put in place

A malleable system is a weak system: it folds easily to the desires of people, it can't be trusted, or be predicted. If we create a community in which any previous agreements can be withdrawn for the sake of "self-improvement", then it will be easily manipulated by whoever has more support in each moment. Top-to-down solutions should not be part of our community values.

> This proposal is lazy.

Indeed. I wrote it quickly. Somebody had to agglutinate the people thinking that it's better to continue with the previous agreements. I hope other people can add better arguments than the ones I'm adding here.

**Comment by Zeptimus** [comment]
[danelsuga]

A malleable system is democracy. What you are criticizing above is democracy. It is not top-to-down.

Top-to-down would be allowing an imbalanced system that eventually permits an elite minority to decide for an entire community, maintaining a status quo that sidelines and harms the majority.

Yes, indeed: “folding easily to the desires of the people” = democracy! 🥰

**Comment by danelsuga** [comment]
My last two comments from the original proposal weren't included above: 

[danelsuga]
“Your economy, your choice.”

https://medium.com/token-engineering-commons/the-token-engineering-commons-hatch-your-economy-your-choice-354926284281


[danelsuga]
I feel like maybe there is some confusion in the interpretation of what is happening here?

The TEC wants to be inclusive and fair.

My feeling is that we cannot comfortably continue with a system where we know that is not happening.

❤️

**Comment by sembrestels** [comment]
TEC is an economy that we have been building during months, we have bootstrapped it from the roots, and each of the decisions has been very participatory. That's why it's "Your economy, your choice", because the community is open to anyone to participate and decide it's future.

All democracies have a sort of constitution that prevents governments to break rules and act as they want on behalf of what the majority has decided. Respecting previous agreements with all the parts involved is what protect communities from [some sorts of  tyranny](https://en.wikipedia.org/wiki/Tyranny_of_the_majority).

**Comment by freedumbs00** [comment]
You completely ignored her concerns.  This is broken.  It was broken from the beginning.  I was a part of praise quant for majority of the praise earned.  It was a small group of people that got to decide what was the value of peoples contribution.  That's a technocracy.   It was from the beginning.  There should have been more involvement of this "community", but it was a task that was not openly communicated.  It was only directed to Stewards.  I wonder why?  What if people would have saw how their contributions were decided by myself or Griff?  We did praise quant all by ourselves for awhile.  Juan joined later then me and him got Zep.  That was the only time we had somewhat of a system but again that system was compromised.  This is waaaaay broken.  Doing nothing and pretending that's okay just reverberates the technocracy.  This is not your choice,  your economy.  It's Their choice, the Economy.  It was always a popularity contest.  If you don't believe me then I should divulge on what praise quant was.  Worse deciding that at the end the solution for TE's is to create some childish banter about "Parties" and just create more debt as an incentive that you care is more then just arrogant it's the Technocracy not wanting people to pull the curtain.

**Comment by LinuxIsCool** [comment]
A reminder, based off of @tamarandom's research on the current tokenlog vote, that 5 people have over 50% of the current voting power.  https://hackmd.io/@KNlVuZ6DRninKfubrrwtzg/r1590is3O

![image](https://user-images.githubusercontent.com/31582215/124624699-f6c80700-de31-11eb-9f4a-2ee1e20b6a5d.png)

I think that the praise system as is over incentivized meeting attendance and under incentivized work done. 

I also want to say that I suggested praise analysis back in October 2020 and was discouraged to do so in favour of doing params hatch modelling. I wish that I had followed my intuition back then and had began the research on praise data, as many of the issues that are surfacing now could have been prevented if they had been discovered early on.

**Comment by sembrestels** [comment]
> This is broken. It was broken from the beginning. I was a part of praise quant for majority of the praise earned.

I've never been a praise quantifier, so I can't speak of how broken it is. If it only was Griff and you during a while, I guess you are co-responsible of how supposedly bad praise quantifying was. Why do you then say that the problem is the technocracy?

It looks like a problem of low participation on praise quantifying parties (I remember praise quantifiers were needed all the time, but volunteers were scarce). It was bad from the beginning, we knew it, but praise quantifying was tedious, and few wanted to spend their weekends doing that. Only now, after months of work and with the hatch close, the interest on this topic has raised.

> 5 people have over 50% of the current voting power

This is not accurate, please follow the conversation in the [forum thread](https://forum.tecommons.org/t/pre-hatch-impact-hours-distribution-analysis/376/81).

> I think that the praise system as is over incentivized meeting attendance and under incentivized work done.

Even if that was the case, people doing work was probably going to meetings as well right? How else could they coordinate with the rest of the community? (I'm not a fan of meetings, and I think they take too much time from working, but it's clear that we can't measure the praise that was not dished, or was not dished often enough, and now it's difficult to recover all those lost praises in a fair way.)

> I also want to say that I suggested praise analysis back in October 2020 and was discouraged to do so in favour of doing params hatch modelling

I guess it wasn't me who discouraged you, but I'm happy you did the modelings. They have provided so much value to the community.

**Comment by tamarandom** [comment]
“This is not accurate, please follow the conversation in the forum thread.”

Hi @sembrestels, with respect, the math is accurate. Over 50% of the voting power applied came from 5 unique addresses. 

I believe what you mean to refer to is @GriffGreen’s suggestion to look at “votes cast” instead of “voting power”, right? I added that, last night, to the forum post you linked to above. 

———

I’m on my phone so can’t do a good copy and paste but here’s a snippet:

I believe the following is a true. Is there a mistake I don’t see? Based on the tokenlog data of the primary voting period:

- it would require 10 of 37 voters, 27% of voters, alone to determine the winner.
- If all other 27 voters combined, 73% of voters, voted for a single but different option, they would not have enough votes to pass it.

—-

Before the 24h extension: 8 out of 30 voters (27%) cast 50% of the total votes.
After the 24h extension: 10 out of 37 voters (27%) cast 50% of the total votes.

**Comment by sembrestels** [comment]
What is not accurate is that "5 people have over 50% of the current voting power".

A high concentration of "voting power applied" may look alarming but we have to be aware is of these possible misconceptions:
* Voting power applied is not votes cast. We use quadratic voting to remove power from the whales.
* 50% of voting power is not concentrated in the hands of 5 whales either (as @LinuxIsCool may be suggesting). If you sum up the top 5 [IH-tokenholders](https://blockscout.com/xdai/mainnet/tokens/0xDF2C3C8764a92Eb43d2eEA0A4C2d77c2306b0835/token-holders), it is 23.22% of voting power, and if we do the same with top 5 [CSTK-tokenholders](https://blockscout.com/xdai/mainnet/tokens/0xc4fbE68522ba81a28879763C3eE33e08b13c499E/token-holders) it is 26,6%. Even if you joined both groups you would not be close to 50%. If "voting power applied" of whales is that high is because of abstention, not because DAO is not controlled by a few hands.

**Comment by tamarandom** [comment]
Hi @sembrestels 

_"Voting power applied is not votes cast. We use quadratic voting to remove power from the whales."_

"Voting power applied" refers to the final cost for the votes cast. So the "quadratic" part of quadratic voting has already been calculated. Do you see what I mean? The results shared are **after** we "use quadratic voting to remove power from the whales". 

Showing is easier than telling so here's a screenshot [from the xls](https://docs.google.com/spreadsheets/d/1lPK8xyoRO8PdVfNKQQ_F90po8cIBZ3Xm-9txnrvkIo4/edit#gid=0). 

![Screen Shot 2021-07-07 at 8 28 05 PM](https://user-images.githubusercontent.com/703624/124812150-8c16e880-df63-11eb-9488-3f2bcd5966ea.png)

To the point of abstention, absolutely. Active voters determine the outcome of votes. Not abstainers. What is educational about this tokenlog data set is that is is empirical. This is what actually happened.

**Comment by sembrestels** [comment]
To my understanding, what it is shown in your [first post](https://forum.tecommons.org/t/pre-hatch-impact-hours-distribution-analysis/376/76) is voting power applied (*cost* in the spreadsheet) and in [the second](https://forum.tecommons.org/t/pre-hatch-impact-hours-distribution-analysis/376/81) it is cast votes (*amount* in the spreadsheet). The quadratic part is only applied in the amount, so "voting power applied" is **before** we "use quadratic voting to remove power from the whales".

Btw this is a discussion I think do not belong to this post, here we are discussing the proposal of not to intervene.
